### ISSUE TITLE
what content to add in last-edition page?

### ISSUE THREAD

**Issue by ArmandDu** [AlsaceDigitale/hhcamp_2015#16]
in page http://alsacedigitale.github.io/hhcamp_wip/last-edition.html

> <insert usefull desceription content here>

by what should this be replaced?

**Comment by sebmade** [comment]
Last event vidéos and websites projects

In March 2014, 19 projects have been realized. Review videos of pitches and look at web page project. It will give you an idea of which amazing things you can do in one week end with your team.
