### ISSUE TITLE
ajouter Gilles Bontemps dans le jury

### ISSUE THREAD

**Issue by sebmade** [AlsaceDigitale/hhcamp_2015#21]

**Comment by sebmade** [comment]
photo http://www.fhpmco.fr/wp-content/uploads/2012/02/BONTEMPS_Gilles_256.jpg

**Comment by sebmade** [comment]
bio : médecin et directeur associé de l’ANAP, l’Agence nationale d’appui à la performance des établissements de santé et médico-sociaux.

**Comment by ArmandDu** [comment]
done,
il manque éventuellement un twitter et un linkedin
