### ISSUE TITLE
ajouter infos complémentaires sur les speakers de future of health

### ISSUE THREAD

**Issue by sebmade** [AlsaceDigitale/hhcamp_2015#23]
un petit texte avec leur bio
un lien vers wikipédia pour marescaux

**Comment by sebmade** [comment]
si pas de texte, mettre n'importe quoi je complèterais

**Comment by ArmandDu** [comment]
quand tu demandes un lien vers wikipedia, c'est une nouvelle id (wikipedia: 'url')  ou dans la description?

**Comment by sebmade** [comment]
dans la description

**Comment by ArmandDu** [comment]
c'est fait a priori, sauf pour les "to be announced soon"
