### ISSUE TITLE
ajouter infos complémentaires sur speaker health data day et un label (technical, legal, medical)

### ISSUE THREAD

**Issue by sebmade** [AlsaceDigitale/hhcamp_2015#24]

**Comment by sebmade** [comment]
reprendre l'idée du label comme sur le site actuel

**Comment by ArmandDu** [comment]
charles Metivier, je lui mets quoi comme label?

**Comment by sebmade** [comment]
medical

**Comment by ArmandDu** [comment]
fait pour health-data-day speakers, je te laisse close le ticket si tout est bon pour toi

**Comment by sebmade** [comment]
alors la où tu as mis le label c'est la qu'il faut mettre une petite bio, c'est bien
par contre c'est plus un label dans le même genre que ce que j'avais fait http://hackinghealth.camp/health-data-day.html pas obligatoirement placé de cette manière mais sous forme de cartouche avec une couleur pour chaque type

**Comment by ArmandDu** [comment]
C'est ce quoi j'avais pensé en premier, mais j'étais tombé sur le design que j'avais fait sur la  [page du hackaton](http://hackinghealth.camp/health-hackathon.html)

**Comment by ArmandDu** [comment]
Pour ce qui est contenu, je peux te le placer. Cependant niveau design, c'est vraiment pas mon fort.
Je te push ce que j'ai.

**Comment by sebmade** [comment]
ok

**Comment by sebmade** [comment]
je vois pas de label, tu as commité ?
je vois juste que tu as rajouté les bios

**Comment by sebmade** [comment]
pour les bios faudrait un tooltip permettant de voir tout le texte (utilise bootstrap)

**Comment by ArmandDu** [comment]
Oups,
Non j'ai enlevé le label (je voyais pas comment le faire et ça cassait tout)
Et je vais voir ça pour le texte.

**Comment by sebmade** [comment]
je regarde comment faire pour le label

**Comment by sebmade** [comment]
j'ai ajouté le label, je te laisse ajouter le tooltip

**Comment by ArmandDu** [comment]
Super merci !
j'étais partis sur la bonne optique sauf que j'ai mal utilisé le main.sass . Merci !

**Comment by ArmandDu** [comment]
done !
restera juste à changer les couleurs et la police selon les gouts

**Comment by sebmade** [comment]
perfect
