### ISSUE TITLE
page press

### ISSUE THREAD

**Issue by sebmade** [AlsaceDigitale/hhcamp_2015#25]
- [x] ajouter un item dans le menu principal
- [x] liens vers le dossier de presse, les pdf d'affiches et de flyers, le kit de communication
- [x] liens vers les newsletters envoyés
-  liens vers les annonces de blog sur l'évènement en mettant le logo du site + le titre
  - \- [x] http://www.ticsante.com/Hacking-Health-Camp-le-hackathon-francais-en-sante-se-dote-de-deux-journees-de-conferences-NS_2121.html
  - \- [x] http://buzz-esante.com/2014/11/12/hacking-health-camp-plus-grand-hackhaton-sante-europeen/
  - \- [x] http://www.alsace-biovalley.com/fr/professionnels-de-sante-participez-au-hacking-health-camp-50h-pour-innover/
  - \- [x] http://www.programmez.com/actualites/hacking-health-camp-le-plus-grand-hackhaton-sante-europeen-21642
  - \- [x] http://www.ehealthnews.eu/events/4119-hacking-health-camp-2015
  - \- [x] http://www.echalliance.com/event/hacking-health-camp/
  - \- [x] http://www.leaderhealth.net/index.php/fr/accueil/12-news-fr/107-digital-health-camp-strasbourg
  - \- [x] http://www.clisp.fr/joomla/evenements/a-venir/343-hacking-health-camp-strasbourg-2015
    http://euronetmrph.org/?p=616
  - \- [x] http://club-digital-sante.info/2014/12/hacking-health-camp-rendez-vous-incontournable-de-la-e-sante-en-2015/
  - \- [x] http://www.congres-medical.com/modules.php?name=3c01_Event&op=plancap_detail&id_plancap=5895
  - \- [x] http://www.dna.fr/sante/2014/12/13/le-militant-de-l-e-sante-donne-rendez-vous
  - \- [ ] https://www.sante-alsace.fr/cms/accueil/les-actualites?template=tpl.newsDetail&newsID=17186 **404 not found**
  - \- [x] http://esante-paysdelaloire.fr/actualites/hacking-health-camp-le-hackathon-francais-en-sante-se-dote-de-deux-journees-de
  - \- [x] http://virchowvillerme.eu/uncategorized/inspire-learn-act-and-build-the-future-of-health-the-largest-european-health-hackaton-will-take-place-in-strasbourg-france-from-the-19th-to-22nd-of-march-2015/
  - \- [x] http://www.alsace-biovalley.com/fr/agenda-evenements/hacking-health-camp-50h-pour-innover-dans-la-sante/
  - \- [x] http://icube.unistra.fr/actualites-agenda/agenda/evenement/?tx_ttnews%5Btt_news%5D=10095&cHash=4b5f0628a3c8bbfa2d7cc2d5e2cd1129

**Comment by ArmandDu** [comment]
J'ai ajouté les blogs avec les logos.

Sinon globalement, il me faudrait des infos sur les point suivants : 
- "liens vers le dossier de presse, les pdf d'affiches" : je ne crois pas avoir ce lien ou je vois pas lequel
- " liens vers les newsletters envoyés" : pareil
- "ajouter un item dans le menu principal" : j'imagine que c'est le menu avec "Event Agenda Ticket ...", cependant dès que je rajoute un élément à ce menu, la mise en page "casse la gueule"
  ![Avant ajout de press](https://cloud.githubusercontent.com/assets/8956043/5239395/0567cf5c-78e0-11e4-9523-85b3d1944d3e.png)

![Avec press](https://cloud.githubusercontent.com/assets/8956043/5239391/e10f1b1a-78df-11e4-84da-b790c820dcb9.png)

**Comment by sebmade** [comment]
à ajouter 
http://www.clisp.fr/joomla/evenements/a-venir/343-hacking-health-camp-strasbourg-2015
http://euronetmrph.org/?p=616

**Comment by sebmade** [comment]
http://club-digital-sante.info/2014/12/hacking-health-camp-rendez-vous-incontournable-de-la-e-sante-en-2015/

**Comment by sebmade** [comment]
faut que tu essayes de trouver un moyen pour que ça tienne dans l'entete, soit réduire la police, soit diminuer l'écart

**Comment by sebmade** [comment]
http://www.congres-medical.com/modules.php?name=3c01_Event&op=plancap_detail&id_plancap=5895

**Comment by sebmade** [comment]
http://www.dna.fr/sante/2014/12/13/le-militant-de-l-e-sante-donne-rendez-vous

**Comment by sebmade** [comment]
https://www.sante-alsace.fr/cms/accueil/les-actualites?template=tpl.newsDetail&newsID=17186

**Comment by sebmade** [comment]
http://esante-paysdelaloire.fr/actualites/hacking-health-camp-le-hackathon-francais-en-sante-se-dote-de-deux-journees-de

**Comment by ArmandDu** [comment]
Salut,

je tombe sur un 404 pour l'url suivante : https://www.sante-alsace.fr/cms/accueil/les-actualites?template=tpl.newsDetail&newsID=17186

Je dois l'ajouter quand même?

**Comment by sebmade** [comment]
http://virchowvillerme.eu/uncategorized/inspire-learn-act-and-build-the-future-of-health-the-largest-european-health-hackaton-will-take-place-in-strasbourg-france-from-the-19th-to-22nd-of-march-2015/

**Comment by sebmade** [comment]
http://www.alsace-biovalley.com/fr/agenda-evenements/hacking-health-camp-50h-pour-innover-dans-la-sante/

**Comment by sebmade** [comment]
http://icube.unistra.fr/actualites-agenda/agenda/evenement/?tx_ttnews%5Btt_news%5D=10095&cHash=4b5f0628a3c8bbfa2d7cc2d5e2cd1129

**Comment by sebmade** [comment]
http://www.sante-alsace.fr/hacking-health-camp-strasbourg-en-2015
http://www.ciusante.org/evenements/hacking-health-camp-19-22-mars-2015-strasbourg/

**Comment by sebmade** [comment]
http://www.e-alsace.net/index.php/smallnews/detail?newsId=17768

**Comment by sebmade** [comment]
http://www.adira.com/evenements/actu-evenements/hacking-health-camp-a-strasbourg-en-mars-2015.html

**Comment by thomas-keck** [comment]
Je m'en occupe, c'est en cours.

**Comment by sebmade** [comment]
http://www.ars.alsace.sante.fr/Hackathon-sante-a-Strasbourg.178946.0.html

**Comment by sebmade** [comment]
http://esante-bretagne.fr/digital-health-camp-hackathon-dedie-la-sante-du-19-au-22-mars-2015/

**Comment by sebmade** [comment]
http://www.dsih.fr/agenda/25/le-hacking-health-renouvelle-l-edition-du-19-au-22-mars-2015-prochain-a-strasbourg.html

**Comment by catherinemosser** [comment]
http://www.lelieududesign.com/actualite/hacking-health-camp-create-the-future-of-healthcare

**Comment by catherinemosser** [comment]
http://www.interopsante.org/offres/gestion/actus_412_22939-994/interop-sante-partenaire-du-hacking-health-camp-du-19-au-22-mars-2015-a-strasbourg.html

**Comment by catherinemosser** [comment]
http://frenchweb.fr/hacking-health-camp/183434

**Comment by sebmade** [comment]
https://www.alsace-esante.fr/alsace-e-sante-partenaire-du-hacking-health-camp

**Comment by sebmade** [comment]
http://www.alsace-biovalley.com/fr/hacking-health-camp-2015-decouvrez-des-prix-dexception-gagner-lors-du-hackathon/

**Comment by sebmade** [comment]
http://www.dsih.fr/article/1374/le-futur-de-la-sante-s-invente-a-strasbourg.html

**Comment by sebmade** [comment]
http://www.medicen.org/evenements/hacking-health-camp

**Comment by thomas-keck** [comment]
J'intègre les liens.

**Comment by sebmade** [comment]
http://www.maddyness.com/agenda/hacking-health-camp-strasbourg/

**Comment by sebmade** [comment]
http://www.alsacreations.com/actu/lire/1664-hacking-health-camp-du-19-au-22-mars-strasbourg.html

**Comment by sebmade** [comment]
http://www.ihu-strasbourg.eu/ihu/hacking-health-camp-du-19-au-22-mars-2015-strasbourg/

**Comment by sebmade** [comment]
http://www.bpifrance.fr/Vivez-Bpifrance/Agenda/Hacking-Health-Camp-2015-13074

**Comment by sebmade** [comment]
http://www.anap.fr/actualites/agenda/detail/actualites/hacking-health-camp-creer-le-futur-de-la-sante/

**Comment by sebmade** [comment]
http://www.softserveinc.com/en-us/news/tackle-medication-adherence/

**Comment by sebmade** [comment]
http://www.hospimedia.fr/actualite/articles/20150306-e-sante-le-hacking-health-camp-devrait-permettre

**Comment by catherinemosser** [comment]
http://www.bureau-alsace.eu/agenda/1922-march-2015-strasbourg-hacking-health-camp/

<edit armand: 404 not found >

**Comment by catherinemosser** [comment]
http://www.shadok.strasbourg.eu/evenement/hacking-health-camp-2015/

**Comment by catherinemosser** [comment]
http://www.alsacreations.com/actu/lire/1664-hacking-health-camp-du-19-au-22-mars-strasbourg.html

**Comment by catherinemosser** [comment]
http://vidalfrance.com/agenda/pharma-success/

**Comment by catherinemosser** [comment]
http://www.silpc.fr/journ-es-hacking-health-camp-du-19-au-22-mars-2015

**Comment by catherinemosser** [comment]
http://filuns.unice.fr/fil/service-communication/evenements-1/hacking-health-camp-du-19-au-22-mars-2015-a-strasbourg

**Comment by catherinemosser** [comment]
http://www.alliancy.fr/agenda/hacking-health-camp

404 not found

**Comment by catherinemosser** [comment]
http://www.isp-paris.org/association/annonces/479-annonces-2015-hacking-health-camp

**Comment by catherinemosser** [comment]
http://psyzoom.blogspot.fr/2015/03/e-sante-le-hacking-health-camp-devrait.html

**Comment by catherinemosser** [comment]
http://www.docaufutur.fr/hacking-health-camp-2015-4-jours-pour-relever-les-defis-sante-de-demain/

**Comment by catherinemosser** [comment]
http://alsagora.blogspot.fr/2015/03/j-10-pour-le-hacking-health-camp-2015.html

**Comment by catherinemosser** [comment]
http://www.formatec.be/portal/Hacking-Health-Camp-du-19-au-22

**Comment by catherinemosser** [comment]
http://up-magazine.info/index.php/actualites/rendez-vous/4276-19-22-mars-hacking-health-camp-2015-a-strasbourg

404 not found

**Comment by catherinemosser** [comment]
http://france3-regions.francetvinfo.fr/alsace/2015/03/15/agenda-de-la-semaine-du-16-au-22-mars-672765.html

**Comment by catherinemosser** [comment]
http://www.tehnopol.ee/et/kalender/sundmuste-kalender&nID=1933

**Comment by catherinemosser** [comment]
http://www.biocat.cat/es/agenda/hacking-health-camp

**Comment by catherinemosser** [comment]
http://www.pharmatalents.es/Encuentros/detalle/80

**Comment by catherinemosser** [comment]
http://www.idigital.cat/web/i-digital/jornades-i-formacio/fires-internacionals/detall/-/asset_publisher/tOi7/content/fira_20150319_hacking-health-camp

**Comment by catherinemosser** [comment]
http://www.informazione.it/c/D486D408-4533-416B-8428-D5BBA68E3A0C/SoftServe-s-Healthcare-Team-to-Tackle-Medication-Adherence-at-the-Hacking-Health-Camp

**Comment by sebmade** [comment]
https://itunes.apple.com/fr/podcast/journal-france-3-19-20-alsace/id285420959?i=337939838&mt=2

**Comment by sebmade** [comment]
http://france3-regions.francetvinfo.fr/alsace/2015/03/19/hacking-health-camp-quand-la-sante-du-futur-passe-par-le-numerique-678145.html

**Comment by sebmade** [comment]
http://www.sciencepresse.qc.ca/actualite/2015/03/18/sante-liberte-numerique

**Comment by catherinemosser** [comment]
http://www.rue89strasbourg.com/index.php/2015/03/19/societe/live-tweet-la-sante-connectee-se-dessine-au-hacking-health-camp/

**Comment by catherinemosser** [comment]
http://www.ciusante.org/evenements/hacking-health-camp-19-22-mars-2015-strasbourg/

already inserted

**Comment by catherinemosser** [comment]
http://france3-regions.francetvinfo.fr/alsace/2015/03/19/hacking-health-camp-quand-la-sante-du-futur-passe-par-le-numerique-678145.html

**Comment by catherinemosser** [comment]
http://esante.gouv.fr/actus/politique-publique/hacking-health-camp-2015-l-evenement-le-plus-innovant-d-europe-en-e-sante

--INSERTION EN COURS, arrêt à ce lien--

**Comment by catherinemosser** [comment]
http://www.europtimist.eu/actualites/hacking-health-camp-le-plus-grand-hackathon-europeen-sur-la-sante-a-strasbourg-du-19-au-22-mars

**Comment by catherinemosser** [comment]
http://www.weblife.fr/evenements/hacking-health-camp-2015

**Comment by catherinemosser** [comment]
https://blogbewhy.wordpress.com/tag/hacking-health-camp/

**Comment by catherinemosser** [comment]
http://www.systematic-paris-region.org/en/evenements/future-health

**Comment by catherinemosser** [comment]
http://centrerhenandesign.com/hacking-health-camp-2015/

**Comment by catherinemosser** [comment]
http://www.vitlab-resater.eu/?q=event/hacking-health-camp-strasbourg-france-march-19th-22nd-2015

**Comment by catherinemosser** [comment]
http://storyofdigitalhealth.com/events/hacking-health-camp/

**Comment by catherinemosser** [comment]
http://www.ehealthnews.eu/events/4119-hacking-health-camp-2015

**Comment by catherinemosser** [comment]
http://www.arcan.fr/actualites/arcan-simplique-dans-linnovation-en-sante.html

**Comment by catherinemosser** [comment]
http://pryv.com/hacking-health-camp-in-strasbourg-march-19th-22th/

**Comment by catherinemosser** [comment]
http://www.leaderhealth.net/index.php/fr/accueil/12-news-fr/107-digital-health-camp-strasbourg

**Comment by catherinemosser** [comment]
http://www.info-culture.com/public/manifestation/116828

**Comment by catherinemosser** [comment]
https://storify.com/SanofiFR/sanofi-au-hacking-health-camp-2015

**Comment by catherinemosser** [comment]
https://medtube.net/events/show/2162/hacking-health-camp

**Comment by catherinemosser** [comment]
http://www.hospimedia.fr/actualite/articles/20150306-e-sante-le-hacking-health-camp-devrait-permettre

already inserted

**Comment by catherinemosser** [comment]
http://www.portailtelesante.org/article.php?sid=8373

**Comment by catherinemosser** [comment]
https://vimeo.com/122884324

**Comment by catherinemosser** [comment]
http://www.get-ehealth.eu/2015/01/12/the-hacking-health-camp-will-use-the-challenges-from-fill-the-gap-to-find-solutions-oriented-to-real-demand/

**Comment by catherinemosser** [comment]
http://biohealthcluster.lu/Events/Hacking-Health-Camp

**Comment by catherinemosser** [comment]
http://pharmageek.fr/hacking-health-camp-healthcare-innovation-in-action-hcsmeufr-inscrivez-vous-et-participez/

**Comment by catherinemosser** [comment]
https://www.medizintechnologie.de/aktuelles/veranstaltungen/zeige/veranstaltung/hacking-health-camp-largest-european-hackathon-on-healthcare/

**Comment by catherinemosser** [comment]
http://www.marketwatch.com/story/softserves-healthcare-team-to-tackle-medication-adherence-at-the-hacking-health-camp-2015-03-10

**Comment by catherinemosser** [comment]
http://www.f6s.com/profile/438901

**Comment by catherinemosser** [comment]
http://www.etiam.fr/actualites-2/

**Comment by catherinemosser** [comment]
http://www.levillagebyca.com/villageois/sanofi

bad content

**Comment by catherinemosser** [comment]
http://www.quantmetry.com/prix-de-linnovation-et-de-la-bpi-france-hhcamp/

**Comment by catherinemosser** [comment]
http://www.industrie-techno.com/porsche-electrique-esprit-start-up-medecine-predictive-les-innovations-qui-re-donnent-le-sourire.37399

**Comment by catherinemosser** [comment]
http://www.pharmatalents.es/Encuentros/detalle/80

already insterted

**Comment by catherinemosser** [comment]
http://www.ticsante.com/print_story.php?story=2307

**Comment by sebmade** [comment]
https://drive.google.com/file/d/0B21GKI0gFqb8ZWJNQjBzT0Z1X1E/view?usp=sharing

**Comment by sebmade** [comment]
https://www.linkedin.com/pulse/2-concepts-i-bring-back-from-hacking-health-camp-s%C3%A9bastien-pourchaire

**Comment by sebmade** [comment]
http://www.journaldunet.com/economie/expert/60354/la-medecine-se-reinvente-au-hacking-health-camp.shtml

**Comment by sebmade** [comment]
http://healthcare.orange.com/a-la-une/a-la-une/imaginer-la-sante-de-demain

**Comment by sebmade** [comment]
http://www.alsace-biovalley.com/fr/hacking-health-camp-bilan-et-palmares-de-ledition-2015/

**Comment by sebmade** [comment]
http://news.doctissimo.fr/Sante/Hacking-Health-Camp-2015-fait-emerger-des-projets-e-sante-de-grande-qualite-40464

**Comment by sebmade** [comment]
http://alsagora.blogspot.fr/2015/03/hacking-health-camp-2015-hhcamp.html

**Comment by sebmade** [comment]
http://www.e-alsace.net/index.php/smallnews/detail?newsId=18223

**Comment by sebmade** [comment]
http://www.assurbanque20.fr/2015/03/24616-le-hackathon-annuel-alsacien-aborde-la-sante-digitale/

**Comment by sebmade** [comment]
http://www.makery.info/2015/03/24/a-strasbourg-on-hacke-fort-pour-reprendre-le-controle-de-sa-sante/

**Comment by sebmade** [comment]
http://www.decisionsante.com/derniere-minute/article/deuxieme-hackathon-en-sante-a-strasbourg-observance-et-education-therapeutique-a-lhonneur/?tx_ttnews%5BbackPid%5D=548&cHash=2e1370d256

**Comment by sebmade** [comment]
http://www.makery.info/en/2015/03/24/a-strasbourg-on-hacke-fort-pour-reprendre-le-controle-de-sa-sante/

**Comment by sebmade** [comment]
http://news.doctissimo.fr/Sante/iPIPI-une-appli-qui-a-de-l-avenir-40560

**Comment by sebmade** [comment]
http://buzz-esante.com/2015/03/31/hacking-health-camp-2015-emergence-de-solutions-davenir/

**Comment by sebmade** [comment]
http://sante.lefigaro.fr/actualite/2015/04/05/23588-marathon-digital-pour-sante-connectee

**Comment by sebmade** [comment]
http://www.zdnet.fr/actualites/hackathons-il-s-agit-maintenant-de-transformer-l-essai-39818362.htm

**Comment by sebmade** [comment]
http://www.digitalcorner-solucom.fr/2015/05/sante-et-innovation-levenement-hacking-health-va-t-il-changer-la-donne/
