### ISSUE TITLE
"Last edition" page is very slow to display

### ISSUE THREAD

**Issue by yannski** [AlsaceDigitale/hhcamp_2015#3]
Is it possible to embed a youtube player with a playlist instead?

**Comment by ArmandDu** [comment]
Hi,
I was looking for a better solution.
But, I' haven't found a way to add a youtube playlist yet.

**Comment by ArmandDu** [comment]
I've pushed some change on the forked repo : https://github.com/ArmandDu/hhcamp_wip/commit/9bcc4571f29e31f51139e04a984dc2d4576ac7de
I've removed the videos and used the youtube playlist instead.

**Comment by yannski** [comment]
Send me a pull request :)

**Comment by ArmandDu** [comment]
is the issue good to be closed now?
