### ISSUE TITLE
ajouter bress healthcare en partenaire (simple)

### ISSUE THREAD

**Issue by sebmade** [AlsaceDigitale/hhcamp_2015#33]
le logo est déjà commité dans le répertoire
site http://bress.healthcare/

**Comment by ArmandDu** [comment]
Salut, escuse moi, mais je ne vois pas le logo dans le répertoire.

**Comment by sebmade** [comment]
img/partner/bress-healthcare.jpg

**Comment by ArmandDu** [comment]
as tu add et push les fichiers?

**Comment by sebmade** [comment]
oups 
c'est bon maintenant
