### ISSUE TITLE
ajouter Joris Muller et Nicolas Griselle dans la team d'organisation

### ISSUE THREAD

**Issue by sebmade** [AlsaceDigitale/hhcamp_2015#34]
la photo de Joris est dans le répertoire déjà
trouver ou demander une photo à Nicolas
trouver leur linkedin et twitter

**Comment by ArmandDu** [comment]
done,

manque le twitter et linkedin de Joris Muller.

**Comment by sebmade** [comment]
https://www.linkedin.com/profile/view?id=262364020
