### ISSUE TITLE
ajouter Nicolas Vayatis comme speaker dans Health Data Day

### ISSUE THREAD

**Issue by sebmade** [AlsaceDigitale/hhcamp_2015#36]
photo http://nvayatis.perso.math.cnrs.fr/nicovaya1.jpg
bio : professeur des universités au département de mathématiques de l'ENS de Cachan et directeur du laboratoire CMLA
website http://nvayatis.perso.math.cnrs.fr/
linkedin https://www.linkedin.com/pub/nicolas-vayatis/b/495/510

**Comment by ArmandDu** [comment]
fait, je l'ai mit en 'technical'.

**Comment by sebmade** [comment]
oui c'est ça c'est bon
