### ISSUE TITLE
update partners

### ISSUE THREAD

**Issue by ArmandDu** [AlsaceDigitale/hhcamp_2015#37]
- vidal : ~~checker sur le drive pour le groupe~~ partner silver
- samsung : ~~checker sur le drive pour le groupe~~ gold
- sanofi : en attente

**Comment by ArmandDu** [comment]
@sebmade tu confirmes le commentaire précédent? : 
- vidal : partner silver
- samsung : partner gold
- sanofi : en attente

**Comment by sebmade** [comment]
oui
