### ISSUE TITLE
ajouter Interaxon en simple partenaire

### ISSUE THREAD

**Issue by sebmade** [AlsaceDigitale/hhcamp_2015#42]

**Comment by ArmandDu** [comment]
je mets quel logo?

logo muse (par interaxon)
![muse](https://cloud.githubusercontent.com/assets/8956043/5548877/bbb0488a-8b7c-11e4-9926-d4d618bb31c5.jpg)
logo interaxon:
![interaxon-logo](https://cloud.githubusercontent.com/assets/8956043/5548892/f0e5023e-8b7c-11e4-8606-860e96ad4cbf.jpg)

**Comment by sebmade** [comment]
interaxon
