### ISSUE TITLE
ajouter le menu EN FR

### ISSUE THREAD

**Issue by sebmade** [AlsaceDigitale/hhcamp_2015#46]

**Comment by sebmade** [comment]
Yann peux tu faire cette modif ce WE STP ?

**Comment by ArmandDu** [comment]
Je me suis permis de d'ajouter les menus.

J'ai fait assez simple mais vue que ça semblais urgent.

**Comment by sebmade** [comment]
merci Armand

**Comment by ArmandDu** [comment]
Il y a t'il des changements/améliorations à faire?
Si oui qui s'en charge?
Si non je peux close l'issue?

**Comment by sebmade** [comment]
faudrait s'inspirer de la maquette si tu peux : https://drive.google.com/open?id=0B21GKI0gFqb8RDFqV1lMcG1iaFU&authuser=0

**Comment by ArmandDu** [comment]
voilà !

**Comment by sebmade** [comment]
nickel
