### ISSUE TITLE
ajouter Bandeau Atelier

### ISSUE THREAD

**Issue by ArmandDu** [AlsaceDigitale/hhcamp_2015#50]

**Comment by sebmade** [comment]
je pense que j'aurais pas le temps, si tu peux t'en occuper ce serait super
suffit juste de rajouter une section au dessus de la section discover, un fond rouge sur texte blanc
ça n'a de sens qu'en fr par contre
et y mettre : Atelier d'information et d'appel à défi le 15 janvier à 19h à la [clinique des diaconesses](lien maps) 
[inscrivez-vous](http://hhatelier2.eventbrite.fr)

**Comment by ArmandDu** [comment]
@sebmade , voilà, t'en penses quoi?

**Comment by sebmade** [comment]
il faudrait le mettre sur la home
et faire l'inverse fond rouge texte blanc
stp

**Comment by ArmandDu** [comment]
@sebmade  voilà !

**Comment by sebmade** [comment]
parfait
