### ISSUE TITLE
Add speakers for hdd

### ISSUE THREAD

**Issue by ArmandDu** [AlsaceDigitale/hhcamp_2015#55]
add here new speakers

**Comment by ArmandDu** [comment]
@sebmade , sur le google doc "partenaire-sponsor-speaker", dans la feuille des speakers HDD, j'ai rajouté une colone 'est sur le site?'

dans les 'confirmé' deux ne sont pas sur le site.
dans la colone 'à confirmer'  James Agnew est sur le site.

Je peux prendre l'initiative de metttre sur le site tous les "confirmé" ?
Si tu me demandes d'ajouter quelqu'un sur le site et qu'il n'est pas dans la bonne section sur le google doc, je peux rafraichir le tableau?

**Comment by sebmade** [comment]
Oui vas y tu peux ajouter tous les confirmes

**Comment by ArmandDu** [comment]
todo :
- [x] Clement Troesch
- [x] Julien Lamy
- [x] Sebastien Jodogne

"Il faudrait ajouter les 3 conférenciers suivants :

Clement Troesch
http://fr.linkedin.com/pub/clément-troesch/a2/342/331/fr

Julien Lamy
Pas d'info complémentaires pour le moment

Sebastien Jodogne
http://linkedin.com/in/jodogne
https://twitter.com/sjodogne"

**Comment by ArmandDu** [comment]
Remove Maresceau

**Comment by ArmandDu** [comment]
- [x] know more about speaker

"Tu peux aussi ajouter
- [x] http://amundsen.com/blog/
  pour Mike Amundsen pour le texte

/Johan
