### ISSUE TITLE
préparer une section "prizes" dans la page hackathon

### ISSUE THREAD

**Issue by sebmade** [AlsaceDigitale/hhcamp_2015#63]
et mettre "to be announced soon"

**Comment by ArmandDu** [comment]
@sebmade , j'ai commit, t'en penses quoi?

**Comment by sebmade** [comment]
je voyais plus des icones comme ça (http://epostmedia.com/wp-content/uploads/2012/11/PrizeBlue03-copy-300x312-288x300.png)
aligner les uns à coté des autres
on ajoutera ensuite le logo du sponsor et le descriptif du pris en 5 lignes en dessous

**Comment by ArmandDu** [comment]
OK, je réfléchis à ça et le fais demain ou ce weekend.

**Comment by sebmade** [comment]
ou encore http://www.flaticon.com/search/prize
et plus particulièrement celui la http://www.flaticon.com/free-icon/sport-recognition-ribbon-badge_59054

**Comment by ArmandDu** [comment]
@sebmade , voilà ce que j'ai imaginé avec ce que tu dis.

![mock-prizes](https://cloud.githubusercontent.com/assets/8956043/5882698/fb7a29fe-a34b-11e4-8fc9-e6837a8d4edd.png)

![mock-prizes2](https://cloud.githubusercontent.com/assets/8956043/5882833/61ed6be6-a34d-11e4-9db5-220fd3b5ab09.png)

**Comment by sebmade** [comment]
ok pour le premier mais sur 3 étages
1 les mentions honorables (10 items MEILLEUR POTENTIEL DE RÉUSSITE, MEILLEURE INNOVATION, MEILLEURE SOLUTION POUR LA COLLABORATION EN SANTÉ, MEILLEURE SOLUTION CLINIQUE, MEILLEURE SOLUTION POUR LES PATIENTS, MEILLEURE SOLUTION VISANT LA SILVER ECONOMIE, MEILLEURE SOLUTION POUR L’ÉDUCATION EN SANTÉ, MEILLEURE SOLUTION POUR LE SYSTÈME DE SANTÉ, PRIX COUP DE COEUR DU JURY, PRIX DU PUBLIC)
2 les prix sponsors (5 items + logo des sponsors + description)
3 le prix bonus (1 item + logo BPIFrance + description)

**Comment by thomas-keck** [comment]
J'ai préparé une version en dur dans le fichier prizes.html
Est-ce que ça vous va ? Sinon il faudra me donner un coup de main pour le rendre dynamique.

**Comment by sebmade** [comment]
ça me va
tu peux d'ores et déjà ajouter les textes des prix : https://docs.google.com/document/d/1hLiCXgZEOJFhFzdBoMKquvFKgfkf8bIJ8aCpJFGO7oc/edit
puis commit que je vois ce que ça donne STP

**Comment by thomas-keck** [comment]
Je viens de voir ton doc. Il y a des textes trop long je pense.
Je vais voir ce que ça donne.
Je commit sur une branch à part.

**Comment by thomas-keck** [comment]
J'ai commit une nouvelle branche feature-prizes : https://github.com/AlsaceDigitale/hhcamp_2015/tree/features-prizes

Par contre j'ai un logo Allianz mais pas Healthcare comme dans des textes. Lequel est le bon du coup ?

**Comment by sebmade** [comment]
c'est interaction healthcare qui fait un prix pas allianz

**Comment by sebmade** [comment]
j'ai mergé et commité, merci c'est nickel
