### ISSUE TITLE
programme future of health

### ISSUE THREAD

**Issue by sebmade** [AlsaceDigitale/hhcamp_2015#66]
mettre à jour le programme avec les infos suivantes 
https://docs.google.com/spreadsheets/d/1yIP4ZR6n3QIoZcLFV1MhmtZ0IYOUI8y5nmf0TzDyLdE/edit#gid=0

indiquer avec un drapeau quand le talk est en français ou en anglais
préciser en haut du programme qu'il y aura la traduction simutanée

**Comment by sebmade** [comment]
prioritaire

**Comment by ArmandDu** [comment]
@sebmade , un example pour l'agenda, j'ai pas encore commit. Il faut améliorer quoi? (j'ai pas encore fait les drapeaux)

![example-agenda-foh](https://cloud.githubusercontent.com/assets/8956043/5808922/2515e1c0-a033-11e4-87e2-12a83071f182.png)

**Comment by ArmandDu** [comment]
![example-agenda-foh](https://cloud.githubusercontent.com/assets/8956043/5808918/1a1bf066-a033-11e4-8bad-77ea1f9cda86.png)

**Comment by sebmade** [comment]
ajouter pour le lunch : Lunch at [La Bourse restaurant](avec le lien vers le restaurant), don't forget to subscribe to the lunch when you register

il faut les drapeaux en effet 
et si possible les têtes des speakers (un peu comme on l'a fait pour http://ngeurope.org/ dans la section scheduling)

**Comment by ArmandDu** [comment]
le lien est faux dans ton commentaire, j'imagine que c'est celui là : http://www.restaurant-de-la-bourse.fr ?

**Comment by sebmade** [comment]
oui

**Comment by ArmandDu** [comment]
j'ai créé une nouvelle branche pour le moment. Je merge une fois finis ;)

**Comment by ArmandDu** [comment]
J'ai fait ça, il reste encore le drapeau à mettre et à voir pour l'alignement du nom.
T'as des retours à me faire à part ces deux points?

**Comment by sebmade** [comment]
C'est ok
Merci

**Comment by ArmandDu** [comment]
"faudrait mettre moins d'espace vide
mettre les titres des talks en plus gros et gras
stp"

**Comment by sebmade** [comment]
tu as pu avancer ?
je voudrais créer aussi le programme pour HDD (je fais une nouvelle issue pour ça)

**Comment by ArmandDu** [comment]
@sebmade , salut. Désolé j'ai pas été sur mon pc ce weekend.

J'essaie d'améliorer le design dans la journée

**Comment by ArmandDu** [comment]
@sebmade , je vois que ce que tu as pour le planning hdd c'est répercuté sur le planning foh.

ça te va le design comme ça du coup?

ps : si j'avais su j'aurai pu commit plus tot. J'avais un rendu similaire avant. Je m'étais dit que ça allait pas car ressemblait pas aux autres images (noir et blanc sur portrait rond).

**Comment by sebmade** [comment]
j'ai fait au plus simple
faudrait maintenant arriver à avoir des ronds et pas des carrés et réduire
la taille des images

**Comment by ArmandDu** [comment]
@sebmade , voilà, j'ai pas réussi à mette le filtre b&w. Si tu le veux, je dupliquerai la balise css.
