### ISSUE TITLE
Update Atelier

### ISSUE THREAD

**Issue by ArmandDu** [AlsaceDigitale/hhcamp_2015#79]
@sebmade ,

vu ton mail, je pense que l'on peut remettre la banière atelier?

Il faut juste que tu me dises quoi mettre.

**Comment by sebmade** [comment]
même message mais tu changes la date et le lieu
inscription : http://hhatelier3.eventbrite.fr

Sébastien Letélié
+33624720496
http://www.linkedin.com/in/sebmade
http://about.me/sebmade

2015-01-27 21:07 GMT+01:00 ArmandDu notifications@github.com:
