### ISSUE TITLE
add Werner Bachmann in Health Data Day speaker as German Health Lawyer

### ISSUE THREAD

**Issue by sebmade** [AlsaceDigitale/hhcamp_2015#8]
ask me for photo and bio

**Comment by ArmandDu** [comment]
added.
todo : 
- add description
- add social links

**Comment by sebmade** [comment]
linkedin https://www.linkedin.com/profile/view?id=19779877
la bio est dans le mail que je t'ai envoyé
met la en allemand pour l'instant
