### ISSUE TITLE
remonter le bandeau "last edition"

### ISSUE THREAD

**Issue by sebmade** [AlsaceDigitale/hhcamp_2015#81]
sur la home et dans la page hackathon
en 3ème section

**Comment by thomas-keck** [comment]
Il se trouvera au-dessus de "Inspire, Learn, Act, 4 days to build the future of health." en home ?
Sur la page Hackathon je ne vois pas du coup.

Merci pour ton retour

**Comment by sebmade** [comment]
oui pour la home
au dessus de hardware & software pour la page hackathon
