### ISSUE TITLE
add Nicolas Cauvet and Charles Metivier as speakers in Health Data Day

### ISSUE THREAD

**Issue by sebmade** [AlsaceDigitale/hhcamp_2015#9]
ask me for photo and bio

**Comment by ArmandDu** [comment]
done,

todo : 
- description and picture for Charles metivier
- ~~translate nicolas's description into english~~
- twitter ~~and linkedins~~ for both people

**Comment by ArmandDu** [comment]
tu me confirme que le linkedin de Charles Metivier est celui ci ? https://www.linkedin.com/profile/view?id=11785464

**Comment by sebmade** [comment]
oui

**Comment by ArmandDu** [comment]
moved issue in #49
