### ISSUE TITLE
ajouter Mathilde dans les speakers de HDD et son talk dans le programme à 13h30 dans le grand amphi

### ISSUE THREAD

**Issue by ArmandDu** [AlsaceDigitale/hhcamp_2015#90]
Mathilde Cavalier est responsable du développement et responsable
du pôle Institutions et Etablissements de Santé de la Direction des
Technologies en Santé (DTS) du CNOP. A ce titre, elle s'occupe du déploiement
du DP en établissements de santé, des services auprès des Institutions et
de la mise en place de partenariats industriels et institutionnels.

**Comment by ArmandDu** [comment]
@sebmade , Il n'y a pas de crénneau HDD pour 13h30 et celui de 14h à déjà deux speakers.
Je crée une troisième colonne à 14h?

**Comment by sebmade** [comment]
non tu crées le créneau de 13h30 - 14h

**Comment by ArmandDu** [comment]
ok !

2015-02-24 16:57 GMT+01:00 Sébastien Letélié notifications@github.com:
