### ISSUE TITLE
r Gilles Mazars dans les speakers HDD et ajouter un talk à 13h30 avec comme titre Samsung SAMI

### ISSUE THREAD

**Issue by ArmandDu** [AlsaceDigitale/hhcamp_2015#91]
Gilles Mazars
in/gmazars

https://www.linkedin.com/in/gmazars

**Comment by ArmandDu** [comment]
@sebmade , comme pour Mathilde Cavalier (#90) au sujet du crénneau de 13h30.

**Comment by sebmade** [comment]
même réponse
tu crées le créneau
